import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles:wght@400;700&family=Nanum+Pen+Script&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Frontend Playground <img src="/favicon.ico" className={styles.image} />
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>See more projects</h2>
            <p>More projects description.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Technologies used</h2>
            <p>Breakdown of our process.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerWrapper}>
          <p className={styles.pFooter}>Made with</p>
          <div className={styles.footerImageDiv}>
            <img src="/heart.ico" className={styles.imageFooter} />
          </div>
          <p className={styles.pFooter}>by</p>
          <div className={styles.footerImageDiv}>
            <img src="/favicon.ico" className={styles.imageFooter} />
          </div> 
        </div>
      </footer>
    </div>
  )
}
